"""some modifications on refresh_tokens

Revision ID: ee858452f1ba
Revises: f170ee2acacc
Create Date: 2025-08-19 01:23:35.471197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee858452f1ba'
down_revision: Union[str, None] = 'f170ee2acacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_os', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_browser', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_column('user_browser')
        batch_op.drop_column('user_os')

    # ### end Alembic commands ###
