"""removed ip address from refresh tokens

Revision ID: f170ee2acacc
Revises: 4de10b388ccb
Create Date: 2025-08-18 13:57:10.196873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f170ee2acacc'
down_revision: Union[str, None] = '4de10b388ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
